// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbeXfK8gO9pCH7Y2E3nYfR-lKFA2-RIO8',
    appId: '1:327881718440:web:851e55a64791012de8609d',
    messagingSenderId: '327881718440',
    projectId: 'airport-project-9cf21',
    authDomain: 'airport-project-9cf21.firebaseapp.com',
    storageBucket: 'airport-project-9cf21.appspot.com',
    measurementId: 'G-01RBYFWVDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhMtsrpmtI4kRpH_r0vDg8PSvqwocReik',
    appId: '1:327881718440:android:153c66158644be3de8609d',
    messagingSenderId: '327881718440',
    projectId: 'airport-project-9cf21',
    storageBucket: 'airport-project-9cf21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHbuIkRqvNmzH0mms61BFSYfLbn9ig51w',
    appId: '1:327881718440:ios:434acacd0e3e1720e8609d',
    messagingSenderId: '327881718440',
    projectId: 'airport-project-9cf21',
    storageBucket: 'airport-project-9cf21.appspot.com',
    iosBundleId: 'com.example.airportProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHbuIkRqvNmzH0mms61BFSYfLbn9ig51w',
    appId: '1:327881718440:ios:1db952c98120cedee8609d',
    messagingSenderId: '327881718440',
    projectId: 'airport-project-9cf21',
    storageBucket: 'airport-project-9cf21.appspot.com',
    iosBundleId: 'com.example.airportProject.RunnerTests',
  );
}
